### PR TITLE
Add keyboard support

### PR DESCRIPTION
**Pull request by LinusCDE**
Part 1 of solving #2 

@Eeems could you test out whether this works on the rM 1? I could test adding and removing keyboards, but broke my flimsy, only Micro-USB-OTG adapter before I could test the new mappings I added:

https://github.com/LinusCDE/doomarkable/blob/f59178caadec880a2e0e4fd572f0a1c3bd5d9b05/src/evdev_keyboard.rs#L162-L270

Mappings are based on [doomkeys.h](https://github.com/ozkl/doomgeneric/blob/613f870b6fa83ede448a247de5a2571092fa729d/doomgeneric/doomkeys.h), with some guesswork based on [this wiki article](https://en.wikibooks.org/wiki/Doom/Controls).

I do not have a folio, and plugging a USB-C-OTG Adapter in didn't make the keyboard appear for me like it did on the rM 1.

### CODE REVIEW

**Comment by LinusCDE** [comment]
Binary based on commit 82a6c47 (using command `cross build --target=armv7-unknown-linux-gnueabihf --release`): [doomarkable.zip](https://github.com/LinusCDE/doomarkable/files/13998393/doomarkable.zip)

**Comment by Eeems** [comment]
```
I_Init: Setting up machine state.
[2024-01-20T19:02:26Z INFO  doomarkable::evdev_keyboard] Keyboard at "/dev/input/event3" detected: keyd virtual keyboard
M_Init: Init miscellaneous info.
thread '<unnamed>' panicked at src/main.rs:282:76:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
R_Init: Init DOOM refresh daemon - ...................
P_Init: Init Playloop state.
S_Init: Setting up sound.
D_CheckNetGame: Checking network game status.
startskill 2  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
Emulating the behavior of the 'Doom 1.9' executable.
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
I_InitGraphics: framebuffer: x_res: 640, y_res: 400, x_virtual: 640, y_virtual: 400, bpp: 32
I_InitGraphics: framebuffer: RGBA: 8888, red_off: 16, green_off: 8, blue_off: 0, transp_off: 24
I_InitGraphics: DOOM screen size: w x h: 320 x 200
I_InitGraphics: Auto-scaling factor: 2
```
This is on my rM2 with keyd running and the folio connected, but after forgetting to run with rm2fb-clien. The app never quits, but never displays. Running with rm2fb-client works as expected. I thought I didn't need to for things built with libremarkable.


On my rM1 it opens and runs fine, but I'm not setup for a fake keyboard unfortunately, so I can't really test that side of the functionality. I'm sure it'll work though if it's working with keyd on the rM2.

**Comment by LinusCDE** [comment]
> This is on my rM2 with keyd running and the folio connected, but after forgetting to run with rm2fb-clien. The app never quits, but never displays. Running with rm2fb-client works as expected. I thought I didn't need to for things built with libremarkable.

I think I'm using an older version of libremarkable here, which didn't include the integrated swtfb client. I created an issue to update it.

**Comment by LinusCDE** [comment]
> On my rM1 it opens and runs fine, but I'm not setup for a fake keyboard unfortunately, so I can't really test that side of the functionality. I'm sure it'll work though if it's working with keyd on the rM2.

Sounds good. I don't expect things like A-Z not to work. But maybe some edge-cases like certain symbols. Some might be missing, but some might also be wrongly mapped. Especially in regards to the keys for the doom controls not being where expected.

When running doomarkable with `RUST_LOG=debug` (or better something like `RUST_LOG=debug:evdev_keyboard,info` to filter out the frame debug messages) it should show if keys were discarded because no mapping was present.

**Comment by LinusCDE** [comment]
I should probably also take a look into keyd. Is that purely a software keyboard or does it require the folio?

**Comment by Eeems** [comment]
> I should probably also take a look into keyd. Is that purely a software keyboard or does it require the folio?

Purely software. It requires the uinput module, and then it grabs all keyboard devices and emits its own events based off of what was pressed and it's mappings to a new evdev device created by uinput. uinput also handles things like key repeat automatically.

https://github.com/toltec-dev/toltec/pull/744 Here is a working package you can use.

You should be able to ignore virtual keyboards when checking to see if a physical keyboard is connected by just checking what bus it's on. I haven't implemented that quite yet, but my code in oxide does filter out keyd specifically:
https://github.com/Eeems-Org/oxide/blob/3ed1bad7a028861e586e703a50cc05fce39a6ec5/shared/liboxide/devicesettings.cpp#L226-L296

I also ignore anything with a vendor or product identifier of 0x0000, which most of the build in input has for some reason.

**Comment by LinusCDE** [comment]
Got to test it now. Seems solid. Makes one really feel the latency now, but still plays way better than with touch.

**Pull request merged**
